apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mural
  labels:
    {{- include "mural.labels" (dict "ctx" $ "component" "ingress") | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {{ .Values.web.service.port }}
